# Generated by Django 5.0.1 on 2024-05-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_adbannerthree_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebannerstwo',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
